pigpioモジュールの使用
UT-solarboatproject/NavigationSystem pull request #47
Opened 2021-06-18 16:02 UTC by MiyashitaT

より精度が高くpwmを読み込めるpigpioモジュールを用いるように修正

2021-06-18 16:15 UTC, MiyashitaT commented
なんか`Some checks were not successful`になってautoblackとかがこけてますけど、これはこのブランチのactionの設定は旧式（autoblack)なのに対してgithub上では新式(autoformat)だからかなと思ってます。
手元でisortとblackを走らせたら普通に通りました。

2021-06-19 02:40 UTC, shiokoala commented on PwmRead.py
> +            if key != self.pin_or:
一時的な措置なのでコメント入れておいたほうがよさそうですね

2021-06-19 02:47 UTC, shiokoala requested changes
自作自演のrequest changeです、このあとすぐ修正コミット出しておきます

2021-06-19 02:47 UTC, shiokoala commented on PwmRead.py
> +        while not all([self.pins[o]["done"] for o in self.pins]):
oが何を指しているのかが自明ではないですね

2021-06-19 02:49 UTC, shiokoala commented on PwmRead.py
> +                "done": False,
doneだけでは何が終わったのかわかりにくいですね

2021-06-19 02:50 UTC, shiokoala approved these changes

2021-06-19 10:26 UTC, shiokoala commented
> なんか`Some checks were not successful`になってautoblackとかがこけてますけど、これはこのブランチのactionの設定は旧式（autoblack)なのに対してgithub上では新式(autoformat)だからかなと思ってます。
> 手元でisortとblackを走らせたら普通に通りました。

autoformatのコミット(dce7ef1b5e55ac3693ba1f99ad94528ec790c29a)をcherry-pickしておきました。

2021-06-20 03:39 UTC, merged